#!/bin/bash

PA="/home/stefano/prog/wallpapers/"
P="/home/stefano/prog/dotfiles/script/background/"

while true
do
    while read LINE
    do
        echo $LINE
        swaymsg "output "*" bg "${PA}${LINE}" fit"
        /usr/bin/sleep $(/usr/bin/cat ${P}time)
    done < ${P}list
done
