#!/bin/bash

PA="/home/stefano/prog/wallpapers/"
P="/home/stefano/prog/dotfiles/script/background/"

while true
do
    while true
    do
        L=$(wc -l ${P}list | awk '{print $1}')
        R=$[RANDOM % L]
        echo $R > /tmp/currentBg.txt
        IMG="$(sed -n "${R}p" "${P}list")" 
        swaymsg output "*" bg "${PA}${IMG}" fit
        /usr/bin/sleep $(/usr/bin/cat ${P}time)
    done
done
