#!/bin/bash

PATH="/home/stefano/prog/dotfiles/script/background/"

while true
do
    while read LINE
    do
        /usr/bin/feh --bg-scale $LINE
        /usr/bin/sleep $(/usr/bin/cat ${PATH}time)
    done < ${PATH}list
done
