#!/bin/bash

SEP=" | "
DATE="$(date +'%d-%m-%Y | %l:%M ')"

BATTERY="$(cat /sys/class/power_supply/BAT1/capacity)"

if [ -z "$BATTERY" ]
then
    BATTERY=""
    BICON=""
else
    BATTERY="${BATTERY}"

    if [ $B -lt 11 ]
    then
        BICON=""
    elif [ $B -lt 41 ]
    then
        BICON=""
    elif [ $B -lt 70 ]
    then
        BICON=""
    elif [ $B -lt 100 ]
    then
        BICON=""
    else
        BICON="" 
    fi
fi
BATTERY="${BATTERY}%"

LIGHT="$(cat /tmp/light.txt)"
LIGHT="$LIGHT%"

FREQ=$(lscpu | grep -i mhz | awk 'FNR == 1 {print$3}')
FREQ="${FREQ::len-4}"
FREQ="${FREQ}MHz"

FREE="$(free used -h | awk 'FNR == 2 {print$3}')"

VOLUME="$(amixer | awk 'FNR == 6 {print$5}')"
VOLUME="${VOLUME#[}"
VOLUME="${VOLUME%]}"
V="${VOLUME%"%"}"
V=$[$V]

if [ "$(amixer | awk 'FNR == 6 {print$6}')" == "[off]" ]
then
    VICON=""
else 
    if [ $V -lt 1 ]
    then
        VICON=""
    elif [ $V -lt 100 ]
    then
        VICON=""
    else
        VICON=""
    fi
fi

echo $SEP

if [ -z "$BATTERY" ]
then
    echo ""
else
    echo $BATTERY $BICON $SEP $LIGHT $SEP
fi

echo $VOLUME $VICON $SEP $FREQ $SEP $FREE $SEP $DATE $SEP
