let mapleader=" "
set encoding=UTF-8
set backspace=indent,eol,start
let g:wrapText=0
imap <C-v> <C-r>0

" go to last line
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"indent
set autoindent
filetype indent on
filetype plugin on
filetype plugin indent on
set omnifunc=syntaxcomplete#Complete

"statusline
set laststatus=2
set statusline+=%f

function! Kformat()
    let line = line('.')
    :norm gg=G
    :exec line
endfunction
map <F5> :call Kformat()<Cr> :call Format()<Cr>

"general mapping
map <C-Esc> :Format()
nmap <Esc><Esc> :w<Cr>
map <leader> @q

"splits
set splitbelow splitright
map <C-h> <C-w>h
map <C-l> <C-w>l
map <C-k> <C-w>k
map <C-j> <C-w>j
nmap <Up> <C-w>+
nmap <Down> <C-w>-
nmap <Left> <C-w><
nmap <Right> <C-w>>

"numbers
set number norelativenumber
map <F2> :set number! norelativenumber<Cr>
map <F3> :set number relativenumber!<Cr>

" general options
set showmode
set showcmd
syntax on
set mouse=i
set confirm
set so=8 "cursor above 8 lines from the bottom of the screen
set wildmenu "bottom menu autocompletion

"text width
set ruler
set colorcolumn=80

"search
set ignorecase
set smartcase
set nohlsearch
set incsearch
set showmatch
map <F4> :set hlsearch!<Cr>

"indent
set smartindent
set expandtab
set smarttab
set shiftwidth=4

"spelling
function SetSpell()
    if &spell == 0
        set spell spelllang=it
    else
        if &spelllang ==# 'it'
            set nospell
            set spell spelllang=en
        else
            set nospell
        endif
    endif
endfunction
map <F6> :call SetSpell()<Cr>

"format to 80 char
function! Format()
    let line = line('.')
    :norm ggVGgq
    :exec line
endfunction

"Plugins
call plug#begin('~/.vim/plugged')
"--dependencies
Plug 'google/vim-maktaba'
Plug 'ryanoasis/vim-devicons'
"---utility
Plug 'junegunn/goyo.vim', { 'on': 'Goyo' }
Plug 'terryma/vim-multiple-cursors'
Plug 'kien/ctrlp.vim', { 'on': 'CtrlP' }
Plug 'francoiscabrol/ranger.vim', { 'on': 'Ranger' }
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'airblade/vim-gitgutter'
"---Programming
Plug 'jiangmiao/auto-pairs'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'neoclide/coc.nvim', {'branch': 'release' }
Plug 'nathanaelkane/vim-indent-guides' 
Plug 'sheerun/vim-polyglot'
"Plug 'arp242/jumpy.vim'
"Plug 'scrooloose/syntastic'
"---languages
Plug 'othree/xml.vim', { 'for': ['xml', 'html'] }
Plug 'ap/vim-css-color'
Plug 'lervag/vimtex', { 'for': 'tex' }
Plug 'suan/vim-instant-markdown', { 'for': 'markdown' }
Plug 'vim-scripts/dbext.vim', { 'for': 'sql' }
"Plug 'bazelbuild/vim-bazel'
"Plug 'justmao945/vim-clang'
call plug#end()

"plugin specific configuraiton
source ~/.vim/confPlugins/polyglot.vim
source ~/.vim/confPlugins/coc.vim
source ~/.vim/confPlugins/ctrlP.vim
source ~/.vim/confPlugins/goyo.vim
source ~/.vim/confPlugins/indentGuides.vim
source ~/.vim/confPlugins/nerdTree.vim
source ~/.vim/confPlugins/ranger.vim

"tabs
noremap <leader>k :tabprevious<Cr>
noremap <leader>j :tabNext<Cr>

" move around
nnoremap E gE
nnoremap <leader>w f 
nnoremap <leader>b F 

