#!/bin/bash

VAR=$(cat /tmp/status.txt)
VAR2=$(cat /tmp/rotation.txt)

if [ $1 == "s" ]
then
    VAR=$[VAR+1]
elif [ $1 == "t" ] 
then
    VAR2=$[VAR2+1]
fi

if [ $VAR -gt 3 ]
then
    VAR=1
fi

if [ $VAR2 -gt 2 ]
then
    VAR2=1
fi

case "$VAR" in
    "1") # monitor
        swaymsg "output DP-2 pos 0 0 enable"
        swaymsg "output HDMI-A-1 disable"
        ;;
    "2") # tv
        swaymsg "output HDMI-A-1 pos 0 0 enable"
        swaymsg "output DP-2 disable"
        ;;
    "3") # double
        swaymsg "output DP-2 pos 1920 0 enable"
        swaymsg "output HDMI-A-1 pos 0 0 enable"
        ;;
esac

if [ $VAR2 == "1" ]
then
    swaymsg output DP-2 transform "0"
else
    swaymsg output DP-2 transform "270"
fi

echo "$VAR" > "/tmp/status.txt"
echo "$VAR2" > "/tmp/rotation.txt"
