#!/bin/bash

P="/home/stefano/.cache/markdown/"
#echo -e "---\noutput: pdf_document\n---\n" > temp
F="$(cat $1 | head -n 1 | awk '{print $2}')"
echo $F
F="${P}${F}.mkd"
touch $F
cat $1 > $F
echo "require(rmarkdown); render('${F}')" | R --vanilla &> /dev/null

sudo ydotool key enter &> /dev/null
sudo ydotool key super+l &> /dev/null
sudo ydotool key r &> /dev/null
sudo ydotool key super+h &> /dev/null

if [ "$2" == "f" ]
then
    gnome-terminal -- firefox --new-window ${F%.mkd}.html &> /dev/null
fi
