alias l='lsd -h'
alias ll='lsd -hl'
alias la='lsd -ha'
alias lla='lsd -hla'
alias tree='lsd -h --tree'

alias v='nvim --cmd "let ena_gui = 1"'
alias vi='nvim --noplugin'
alias t='floaterm'
alias diff='diff --color'
alias less=$PAGER

alias a='pikaur --color=always'
alias p='sudo pacman'
alias q='xbps-query -Rs'
alias i='sudo xbps-install'
alias s='sudo xbps-install -S'
alias u='sudo xbps-install -Su'
alias r='sudo xbps-remove'

alias grep="grep --color"
alias fgrep="fgrep --color"
alias egrep="egrep --color"

alias clone='git clone --recursive'
alias pull='git pull'
alias commit='git commit'
alias commim='git commit -m'
alias commia='git commit --amend'
alias push='git push'
alias pusf='git push -f'
alias merge='git merge'
alias add='git add'
alias adda='git add -A'
alias branch='git branch'
alias branca='git branch --all'
alias remotv='git remote -v'
alias rebasi='git rebase -i'
alias gsw='git switch'
alias glog='git log --color=always'
alias glol='git log --pretty=oneline --color=always'
alias gshow='git show'
alias gdiff='git diff --color'
alias gstatus='git status'
alias greset='git reset'
alias grestore='git restore'

alias xamt='sudo xampp start'
alias xamr='sudo xampp start'
alias xamp='sudo xampp stop'
