#!/bin/bash

SEP=" | "
DATE="$(date +'%d-%m-%Y | %l:%M ')"

BATTERY="$(acpi | awk '{print $4}' )"
if [ -z "$BATTERY" ]
then
    BATTERY=""
    BICON=""
else
    BATTERY="${BATTERY::len-1}"
    B=$[${BATTERY::len-1}]

    if [ $B -lt 11 ]
    then
        BICON=""
    elif [ $B -lt 41 ]
    then
        BICON=""
    elif [ $B -lt 70 ]
    then
        BICON=""
    elif [ $B -lt 100 ]
    then
        BICON=""
    else
        BICON="" 
    fi
    BATTERY="${SEP} ${BATTERY}"
fi

LIGHT="$(light -G)"

FREE="$(free used -h | awk 'FNR == 2 {print$3}')"

echo $DATE $SEP $FREE $BATTERY $BICON $SEP $LIGHT""

